# Generated by Django 5.0.3 on 2024-03-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_number', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('supervisor', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
