# Generated by Django 5.0.4 on 2024-04-27 06:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus', models.CharField(choices=[('Casuarina', 'Casuarina'), ('Sydney', 'Sydney'), ('External', 'External')], max_length=20, primary_key=True, serialize=False, verbose_name='Campus Name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(choices=[('Artificial Intelligence, Machine Learning and Data Science', 'Artificial Intelligence, Machine Learning and Data Science'), ('Biomedical Engineering and Health Informatics', 'Biomedical Engineering and Health Informatics'), ('Cyber Security', 'Cyber Security')], max_length=100, primary_key=True, serialize=False, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.CharField(choices=[('Chemical Engineering', 'Chemical Engineering'), ('Civil and Structural Engineering', 'Civil and Structural Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Computer Science', 'Computer Science'), ('Cyber Security', 'Cyber Security'), ('Data Science', 'Data Science'), ('Information Systems and Data Science', 'Information Systems and Data Science'), ('Software Engineering', 'Software Engineering')], max_length=50, primary_key=True, serialize=False, verbose_name='Course Name')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('supervisor', models.CharField(choices=[('Bharanidharan Shanmugam', 'Bharanidharan Shanmugam'), ('Yakub Sebastian', 'Yakub Sebastian'), ('Sami Azam', 'Sami Azam'), ('Asif Karim', 'Asif Karim')], max_length=50, primary_key=True, serialize=False, verbose_name='Supervisor Name')),
            ],
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('topic_number', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Thesis Number')),
                ('title', models.CharField(max_length=100, verbose_name='Thesis Title')),
                ('description', models.TextField(verbose_name='Thesis Description')),
                ('campus', models.ManyToManyField(to='main.campus', verbose_name='Campus Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.category', verbose_name='Category Name')),
                ('course', models.ManyToManyField(to='main.course', verbose_name='Course Name')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.supervisor', verbose_name='Supervisor Name')),
            ],
        ),
    ]
