# Generated by Django 5.0.3 on 2024-03-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='course',
        ),
        migrations.AddField(
            model_name='thesis',
            name='campus',
            field=models.ManyToManyField(to='main.campus'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='course',
            field=models.ManyToManyField(to='main.course'),
        ),
    ]
