# Generated by Django 5.0.3 on 2024-04-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_campus_course_remove_thesis_campus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='course',
        ),
        migrations.DeleteModel(
            name='Campus',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
